server:
  AppMode: debug
  HttpPort: 8080
  JwtKey: YourJwtKey
  JwtIssuer: PICC
  PostImages: ./images/post/
  ProfileImages: ./images/profile/
datasource:
  dirverName: mysql
  host: localhost
  port: 3306
  database: picc
  username: root
  password: 123456
  charset: utf8
